### ISSUE TITLE
scene.pick()获取Cesium3DTileFeature对象的时候，报错

### ISSUE THREAD

**Issue by wangjy431** [fuzhenn/maptalks.cesium#1]
cesiumLayer.getMap().on('mousedown', (function(e){
    var ces = new Cesium.Cartesian2(e.containerPoint.x,e.containerPoint.y);
    console.log(ces);
    var pickedFeature = scene.pick(ces);
    console.log(pickedFeature);
  }));

![image](https://user-images.githubusercontent.com/25605696/62023645-67a52400-b204-11e9-866c-2b2bf86ff99a.png)

**Comment by fuzhenn** [comment]
不是很清楚，这个错误可能要从cesium方面定位错误原因

**Comment by deyihu** [comment]
this is fixed by https://github.com/fuzhenn/maptalks.cesium/blob/258a0825e9c2b6a82e2c8ce92d578813c899eeb2/index.js#L293
